Readiness review
aws-cloudformation/aws-cloudformation-resource-providers-events pull request #23
Opened 2023-05-17 16:59 UTC by Disciple153

*Issue #, if available:*

*Description of changes:*
Addressed issues mentioned in Readiness Review:
- Added stabilization to CreateHandler
- Use StackId to check for CCAPI instead of targets list
- Put ListHandler in callgraph
- Deleted existence chack from UpdateHandler
- Fixed return statements of mitigateFailed handlers to return most up to date data
- handled ThrottlingException in:
  - handleError
  - CreateHandler pre-existence check
  - stabilization
- Fixed unit tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-17 17:11 UTC, nndanisa reviewed
Looks good

2023-05-17 22:32 UTC, karlijb requested changes
Changes look good overall, but Create handler needs to be reviewed

2023-05-22 22:26 UTC, karlijb approved these changes

2023-05-22 22:50 UTC, nndanisa approved these changes

2023-05-23 14:43 UTC, merged